<a href="https://colab.research.google.com/github/pentakll4002/numpyPandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

## Create array using numpy
## Create a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## Reshape - ;à mảng 2 chiều
arr2 = np.array([1, 2, 3, 4, 5])
## Reshape(1, 5) nghĩa là 1 hàng 5 cột
arr2.reshape(1, 5)


array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [ ]:
### 2D array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
arr2.shape
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
## Tạo mảng 1 chiều từ 0 -> 9, và in ra các phần tử chẳn, tạo ra 5 hàng, 1 cột
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
## Tạo ra ma trận 3 hàng 4 cột full 1
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
### Identity Matrix =>>> Ma trận chéo, ma trận tam giác
# Tạo ma trận tam giác 3x3
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
### Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
### Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### Element Wise addition
print ("Addition:", arr1 + arr2)

### Element Wise Substraction
print ("Substraction:", arr1 - arr2)

### Element Wise Multiplication
print("Multiplication:", arr1 * arr2)

### Element Wise Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiple: [ 10  40  90 160 250]
Distract: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
### Universal Function
arr = np.array([2, 3, 4, 5, 6])

### Square root : Khai căn
print(np.sqrt(arr))

### Exponential : Hàm số mũ
print(np.exp(arr))

### Sine : Sin
print(np.sin(arr))

### Logarit =>> Hàm số log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
### Array Licing and Indexing

# Tạo ra mảng 2 chiều 3 dòng 4 cột
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


1

In [ ]:
## Lấy hàng đầu tiên của arr
print(arr[0][0])

1

In [ ]:
## Lấy số 7 và 8
print(arr[1][2])
print(arr[1][3])

8

In [ ]:
## Lấy từ hàng 2 đổ đi
print(arr[1:])

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
## Lấy từ hàng 2, và lấy cột 3 đổ đi
print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [ ]:
## Lấy số 2, 3, 4, 6, 7, 8
print(arr[0:2, 1:])
## Lấy số 7,8, 11, 12
print(arr[1:, 2:])
## Lây số 6, 7, 8, 10, 11, 12
print(arr[1:, 1:])
## Lấy số 6, 7, 10, 11
print(arr[1:, 1:3])

[[2 3 4]
 [6 7 8]]
[[ 7  8]
 [11 12]]
[[ 6  7  8]
 [10 11 12]]
[[ 6  7]
 [10 11]]


In [ ]:
### Modify array element
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Statistical Concept---Normalization


In [ ]:
## To have a mean of 0 and standard deviation of 1: Độ lệch chuẩn từ 0 -> 1
data = np.array([1, 2, 3, 4, 5])

### Calculate the mean and standard deviation
## mean = giá trị trung bình
## std = độ lệch chuẩn
# X là giá trị dữ liệu gốc
# x̄ (x-bar) là giá trị trung bình của tập dữ liệu
# std là độ lệch chuẩn của tập dữ liệu
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

### Output:
### Normalized data: [-1.2649106 -0.63245553 0. 0.63245553 1.2649106]


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

### Mean
mean = np.mean(data)
print("Mean:", mean)

### Median
median = np.median(data)
print("Median:", median)

### Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

### Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
### Logical operation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

### Lấy các phần tử lớn hơn 5 (bên trong là điều kiện) và bé hơn 8
data[ (data >= 5) & (data <= 8) ]

array([5, 6, 7, 8])